[package]
name = "client"
version = "0.1.0"
edition = "2021"
authors = ["Ben <bensnedeker1@gmail.com>", "Eric <skepz.dev@gmail.com>"]
description = "The client implementation for aether"

[dependencies]
better_term = "*"
send-it = "0.1.5"

[dependencies.aether-common]
path = "../aether-common"