[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Ben <bensnedeker1@gmail.com>", "Eric <skepz.dev@gmail.com>"]
description = "The server implementation for aether"

[dependencies]
better_term = "*"
send-it = "*"

[dependencies.logger]
path = "../logger"